export const defaultPacks = [
  {
    id: "create-above-and-beyond",
    name: "机械动力：星辰大海 (Create: Above and Beyond)",
    version: "1.16.5",
    loader: "Forge",
    memoryReq: "6GB - 8GB",
    category: "科技 / 自动化",
    tags: ["科技", "机械动力", "任务驱动", "太空探索"],
    description: "以机械动力（Create）为核心的划时代科技包。从传动齿轮、自动化流水线到建造登月火箭，每一步都环环相扣，极为优雅！",
    link: "https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "all-the-mods-9",
    name: "全知之物 9 (All The Mods 9 - ATM9)",
    version: "1.20.1",
    loader: "Forge / NeoForge",
    memoryReq: "8GB - 12GB",
    category: "综合 / 全能",
    tags: ["全能全家桶", "科技", "魔法", "终极神器"],
    description: "现代版本最受欢迎的全家桶！涵盖400+模组，兼顾应用能源、热力、新生魔艺与格雷工业分支，以合成全知之星为终极荣耀。",
    link: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-9",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "gt-new-horizons",
    name: "格雷科技：新地平线 (GT: New Horizons)",
    version: "1.7.10",
    loader: "Forge",
    memoryReq: "6GB - 8GB",
    category: "硬核 / 工业修仙",
    tags: ["硬核", "格雷科技", "长线修仙", "终极联机"],
    description: "MC史上内容深度最惊人的工业整合包，精心维护更新超十年。拥有极严密的科技树跃迁与数千种材料合成，适合长期稳定开荒！",
    link: "https://gtnewhorizons.com",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "cobblemon-reborn",
    name: "宝可梦：世代重铸 (Cobblemon Reborn)",
    version: "1.20.1",
    loader: "Fabric / Forge",
    memoryReq: "4GB - 6GB",
    category: "休闲 / 冒险",
    tags: ["宝可梦", "休闲养老", "开放世界", "轻量低配"],
    description: "完美契合MC原版方块画风的新一代宝可梦整合包！流畅无违和感，支持野外即时抓宠、培养配种、搭建道馆与群友PVP切磋。",
    link: "https://cobblemon.com",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "vault-hunters-3",
    name: "穹顶之战 (Vault Hunters 3rd Edition)",
    version: "1.18.2",
    loader: "Forge",
    memoryReq: "8GB+",
    category: "RPG / 地牢刷宝",
    tags: ["RPG", "地牢闯关", "技能树", "刷宝开箱"],
    description: "类暗黑/流放之路风格的动作刷宝RPG！制作水晶开启异界穹顶，探索限时地牢、击败Boss、解锁强大天赋技能和定制传说道具。",
    link: "https://vaulthunters.gg",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "scape-and-run-parasites",
    name: "寄生虫：末日天灾 (Scape and Run)",
    version: "1.12.2",
    loader: "Forge",
    memoryReq: "6GB+",
    category: "生存 / 恐怖硬核",
    tags: ["末日生存", "硬核防御", "寄生生物", "团队协作"],
    description: "极度刺激的硬核末日！寄生生物会随世界天数进化蔓延、吞噬地形。群友必须抱团筑城设防、研发自动化军火抵御一波波尸潮。",
    link: "https://www.curseforge.com/minecraft/modpacks/parasites",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "create-astral",
    name: "机械动力：星空列车 (Create: Astral)",
    version: "1.18.2",
    loader: "Fabric",
    memoryReq: "6GB+",
    category: "科技 / 探索",
    tags: ["机械动力", "星际列车", "太空", "优秀优化"],
    description: "铺设跨越行星的星际铁路！将机械动力与火箭科技巧妙融合，在月球和火星建造大型工业基地，Fabric端极佳的运行帧率与视觉效果。",
    link: "https://www.curseforge.com/minecraft/modpacks/create-astral",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "vanilla-plus-performance",
    name: "原版增强与生电拓展 (Vanilla+ Performance)",
    version: "1.21",
    loader: "Fabric",
    memoryReq: "4GB+",
    category: "原版增强 / 生电",
    tags: ["原生优化", "生电工程", "养老摸鱼", "低配高帧"],
    description: "以极致帧率优化（Sodium+Iris光影）、红石生电便利工具（投影/投掷）及细致视觉提升为主，不破坏原版机制，适合养老与建筑。",
    link: "",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  }
];
