export const defaultPacks = [
  {
    id: "dawncraft",
    name: "破晓之界 (DawnCraft: Echoes of Legends)",
    version: "1.18.2",
    loader: "Forge",
    memoryReq: "8GB - 10GB",
    category: "RPG / 类魂动作",
    tags: ["类魂动作", "硬核RPG", "史诗Boss", "剧情任务"],
    description: "B站与国内社区现象级“类魂动作 (Souls-like)”大作！彻底重构了翻滚、招架与武器连招战斗模组，包含大量独立剧情任务、NPC全语音以及极具攻坚挑战性的史诗级世界Boss！",
    link: "https://www.mcmod.cn/modpack/521.html",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "create-astral",
    name: "机械动力：星空列车 (Create: Astral)",
    version: "1.18.2",
    loader: "Fabric",
    memoryReq: "6GB+",
    category: "科技 / 探索",
    tags: ["机械动力", "星际列车", "太空", "优秀优化"],
    description: "铺设跨越行星的星际铁路！将机械动力与火箭科技巧妙融合，在月球和火星建造大型工业基地，Fabric端极佳的运行帧率与视觉效果。",
    link: "https://www.curseforge.com/minecraft/modpacks/create-astral",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "prominence-2",
    name: "卓越 2 RPG (Prominence II RPG)",
    version: "1.20.1",
    loader: "Fabric",
    memoryReq: "6GB - 8GB",
    category: "RPG / 魔法科技",
    tags: ["天赋树", "暗黑刷宝", "次时代UI", "Modrinth热门"],
    description: "Modrinth 长期高居下载榜前列的次时代 RPG 神作！深度融入类似流放之路的庞大天赋树系统、传奇怪物掉落与精美UI，完美平衡了次世代魔法与机械动力自动化。",
    link: "https://modrinth.com/modpack/prominence-2-fabric",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "gt-new-horizons",
    name: "格雷科技：新地平线 (GT: New Horizons)",
    version: "1.7.10",
    loader: "Forge",
    memoryReq: "6GB - 8GB",
    category: "硬核 / 工业修仙",
    tags: ["硬核", "格雷科技", "长线修仙", "终极联机"],
    description: "MC史上内容深度最惊人的工业整合包，精心维护更新超十年。拥有极严密的科技树跃迁与数千种材料合成，适合长期稳定开荒！",
    link: "https://gtnewhorizons.com",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "stoneblock-3",
    name: "石头世界 3 (Stoneblock 3)",
    version: "1.18.2",
    loader: "Forge",
    memoryReq: "6GB - 8GB",
    category: "科技 / 空岛变种",
    tags: ["地下空岛", "无中生有", "科技魔法", "休闲任务"],
    description: "经典“反向空岛”代表作。四周全是被坚固岩石包裹的地下世界，无需担心失足跌入虚空，通过石磨与筛网无中生有，打造地下科技工业帝国！",
    link: "https://www.mcmod.cn/modpack/507.html",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "deceasedcraft",
    name: "亡灵启示录 (DeceasedCraft - 现代末日废土)",
    version: "1.18.2",
    loader: "Forge",
    memoryReq: "8GB - 10GB",
    category: "生存 / 现代末日",
    tags: ["现代枪械", "丧尸废土", "载具驾驶", "团队求生"],
    description: "Modrinth 与 MC百科热度极高的丧尸天灾生存包！包含深度枪械改装射击（TACZ）、汽车与直升机驾驶、现代废墟城市搜刮与尸潮防御，极具电影感！",
    link: "https://modrinth.com/modpack/deceasedcraft",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "cobblemon-reborn",
    name: "宝可梦：世代重铸 (Cobblemon Reborn)",
    version: "1.20.1",
    loader: "Fabric / Forge",
    memoryReq: "4GB - 6GB",
    category: "休闲 / 冒险",
    tags: ["宝可梦", "休闲养老", "开放世界", "轻量低配"],
    description: "完美契合MC原版方块画风的新一代宝可梦整合包！流畅无违和感，支持野外即时抓宠、培养配种、搭建道馆与群友PVP切磋。",
    link: "https://cobblemon.com",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "vault-hunters-3",
    name: "穹顶之战 (Vault Hunters 3rd Edition)",
    version: "1.18.2",
    loader: "Forge",
    memoryReq: "8GB+",
    category: "RPG / 地牢刷宝",
    tags: ["RPG", "地牢闯关", "技能树", "刷宝开箱"],
    description: "类暗黑/流放之路风格的动作刷宝RPG！制作水晶开启异界穹顶，探索限时地牢、击败Boss、解锁强大天赋技能和定制传说道具。",
    link: "https://vaulthunters.gg",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
  {
    id: "scape-and-run-parasites",
    name: "寄生虫：末日天灾 (Scape and Run)",
    version: "1.12.2",
    loader: "Forge",
    memoryReq: "6GB+",
    category: "生存 / 恐怖硬核",
    tags: ["末日生存", "硬核防御", "寄生生物", "团队协作"],
    description: "极度刺激的硬核末日！寄生生物会随世界天数进化蔓延、吞噬地形。群友必须抱团筑城设防、研发自动化军火抵御一波波尸潮。",
    link: "https://www.curseforge.com/minecraft/modpacks/parasites",
    isPreset: true,
    author: "服主预设",
    suggestedBy: "管理员",
    votes: [],
    createdAt: "2026-09-01T00:00:00.000Z"
  },
];
